/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CourseId = IDL.Nat;
export const CreateCourseDto = IDL.Record({ 'title' : IDL.Text });
export const Time = IDL.Int;
export const Course = IDL.Record({
  'id' : CourseId,
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'isPublished' : IDL.Bool,
  'views' : IDL.Nat,
  'createdAt' : Time,
  'tags' : IDL.Vec(IDL.Text),
  'instructorId' : IDL.Principal,
  'lessonCount' : IDL.Nat,
});
export const CreateUserProfileDto = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const ProfileId = IDL.Nat;
export const UserProfile = IDL.Record({
  'id' : ProfileId,
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Time,
  'role' : UserRole,
  'email' : IDL.Text,
  'avatarUrl' : IDL.Text,
});
export const EmailUserPublic = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'role' : IDL.Text,
  'email' : IDL.Text,
});
export const Review = IDL.Record({
  'principal' : IDL.Principal,
  'createdAt' : Time,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
  'courseId' : CourseId,
});
export const Enrollment = IDL.Record({
  'completedAt' : IDL.Opt(Time),
  'principal' : IDL.Principal,
  'isCompleted' : IDL.Bool,
  'enrolledAt' : Time,
  'courseId' : CourseId,
});
export const Badge = IDL.Record({ 'name' : IDL.Text, 'awardedAt' : Time });
export const LessonProgress = IDL.Record({
  'lessonId' : IDL.Text,
  'completedAt' : IDL.Opt(Time),
  'isCompleted' : IDL.Bool,
  'courseId' : CourseId,
});
export const QuizAttempt = IDL.Record({
  'completedAt' : Time,
  'score' : IDL.Nat,
  'pointsEarned' : IDL.Nat,
  'quizId' : IDL.Text,
  'courseId' : CourseId,
  'attemptNumber' : IDL.Nat,
});
export const LearnerCourseReport = IDL.Record({
  'completedAt' : IDL.Opt(Time),
  'learnerPrincipal' : IDL.Principal,
  'startedAt' : IDL.Opt(Time),
  'isCompleted' : IDL.Bool,
  'completedLessons' : IDL.Nat,
  'enrolledAt' : Time,
  'courseId' : CourseId,
});
export const UpdateCourseDto = IDL.Record({
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'isPublished' : IDL.Bool,
  'tags' : IDL.Vec(IDL.Text),
  'lessonCount' : IDL.Nat,
});
export const UpdateUserProfileDto = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'awardBadge' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'completeCourse' : IDL.Func([CourseId], [], []),
  'createCourse' : IDL.Func([CreateCourseDto], [Course], []),
  'createProfile' : IDL.Func([CreateUserProfileDto], [UserProfile], []),
  'deleteEmailUser' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'doesAdminExist' : IDL.Func([], [IDL.Bool], ['query']),
  'enrollCourse' : IDL.Func([IDL.Record({ 'courseId' : CourseId })], [], []),
  'enrollLearnerByEmail' : IDL.Func([CourseId, IDL.Text], [], []),
  'getAllEmailUsers' : IDL.Func([], [IDL.Vec(EmailUserPublic)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCourseAttendees' : IDL.Func(
      [CourseId],
      [IDL.Vec(UserProfile)],
      ['query'],
    ),
  'getCourseReviews' : IDL.Func([CourseId], [IDL.Vec(Review)], ['query']),
  'getCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getEmailUserById' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : EmailUserPublic, 'err' : IDL.Text })],
      ['query'],
    ),
  'getEnrollments' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Enrollment)],
      ['query'],
    ),
  'getMyBadges' : IDL.Func([], [IDL.Vec(Badge)], ['query']),
  'getMyCourseCompletions' : IDL.Func([], [IDL.Vec(Enrollment)], ['query']),
  'getMyCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getMyLessonProgress' : IDL.Func(
      [CourseId],
      [IDL.Vec(LessonProgress)],
      ['query'],
    ),
  'getMyPoints' : IDL.Func([], [IDL.Nat], ['query']),
  'getMyQuizAttempts' : IDL.Func(
      [CourseId, IDL.Text],
      [IDL.Vec(QuizAttempt)],
      ['query'],
    ),
  'getReportingData' : IDL.Func([], [IDL.Vec(LearnerCourseReport)], ['query']),
  'getUserCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
  'incrementCourseViews' : IDL.Func([CourseId], [], []),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'loginEmailUser' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : EmailUserPublic, 'err' : IDL.Text })],
      ['query'],
    ),
  'markLessonComplete' : IDL.Func([CourseId, IDL.Text], [], []),
  'registerEmailUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : EmailUserPublic, 'err' : IDL.Text })],
      [],
    ),
  'resetDatabase' : IDL.Func([], [], []),
  'resetEmailUsers' : IDL.Func([], [], []),
  'seedFirstAdmin' : IDL.Func([], [], []),
  'setUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'submitQuizAttempt' : IDL.Func(
      [CourseId, IDL.Text, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'submitReview' : IDL.Func([CourseId, IDL.Nat, IDL.Text], [], []),
  'updateCourse' : IDL.Func([CourseId, UpdateCourseDto], [Course], []),
  'updateEmailUserRole' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateMyProfile' : IDL.Func([UpdateUserProfileDto], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CourseId = IDL.Nat;
  const CreateCourseDto = IDL.Record({ 'title' : IDL.Text });
  const Time = IDL.Int;
  const Course = IDL.Record({
    'id' : CourseId,
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'isPublished' : IDL.Bool,
    'views' : IDL.Nat,
    'createdAt' : Time,
    'tags' : IDL.Vec(IDL.Text),
    'instructorId' : IDL.Principal,
    'lessonCount' : IDL.Nat,
  });
  const CreateUserProfileDto = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
  });
  const ProfileId = IDL.Nat;
  const UserProfile = IDL.Record({
    'id' : ProfileId,
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Time,
    'role' : UserRole,
    'email' : IDL.Text,
    'avatarUrl' : IDL.Text,
  });
  const EmailUserPublic = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'role' : IDL.Text,
    'email' : IDL.Text,
  });
  const Review = IDL.Record({
    'principal' : IDL.Principal,
    'createdAt' : Time,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
    'courseId' : CourseId,
  });
  const Enrollment = IDL.Record({
    'completedAt' : IDL.Opt(Time),
    'principal' : IDL.Principal,
    'isCompleted' : IDL.Bool,
    'enrolledAt' : Time,
    'courseId' : CourseId,
  });
  const Badge = IDL.Record({ 'name' : IDL.Text, 'awardedAt' : Time });
  const LessonProgress = IDL.Record({
    'lessonId' : IDL.Text,
    'completedAt' : IDL.Opt(Time),
    'isCompleted' : IDL.Bool,
    'courseId' : CourseId,
  });
  const QuizAttempt = IDL.Record({
    'completedAt' : Time,
    'score' : IDL.Nat,
    'pointsEarned' : IDL.Nat,
    'quizId' : IDL.Text,
    'courseId' : CourseId,
    'attemptNumber' : IDL.Nat,
  });
  const LearnerCourseReport = IDL.Record({
    'completedAt' : IDL.Opt(Time),
    'learnerPrincipal' : IDL.Principal,
    'startedAt' : IDL.Opt(Time),
    'isCompleted' : IDL.Bool,
    'completedLessons' : IDL.Nat,
    'enrolledAt' : Time,
    'courseId' : CourseId,
  });
  const UpdateCourseDto = IDL.Record({
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'isPublished' : IDL.Bool,
    'tags' : IDL.Vec(IDL.Text),
    'lessonCount' : IDL.Nat,
  });
  const UpdateUserProfileDto = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'awardBadge' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'completeCourse' : IDL.Func([CourseId], [], []),
    'createCourse' : IDL.Func([CreateCourseDto], [Course], []),
    'createProfile' : IDL.Func([CreateUserProfileDto], [UserProfile], []),
    'deleteEmailUser' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'doesAdminExist' : IDL.Func([], [IDL.Bool], ['query']),
    'enrollCourse' : IDL.Func([IDL.Record({ 'courseId' : CourseId })], [], []),
    'enrollLearnerByEmail' : IDL.Func([CourseId, IDL.Text], [], []),
    'getAllEmailUsers' : IDL.Func([], [IDL.Vec(EmailUserPublic)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCourseAttendees' : IDL.Func(
        [CourseId],
        [IDL.Vec(UserProfile)],
        ['query'],
      ),
    'getCourseReviews' : IDL.Func([CourseId], [IDL.Vec(Review)], ['query']),
    'getCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getEmailUserById' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : EmailUserPublic, 'err' : IDL.Text })],
        ['query'],
      ),
    'getEnrollments' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Enrollment)],
        ['query'],
      ),
    'getMyBadges' : IDL.Func([], [IDL.Vec(Badge)], ['query']),
    'getMyCourseCompletions' : IDL.Func([], [IDL.Vec(Enrollment)], ['query']),
    'getMyCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getMyLessonProgress' : IDL.Func(
        [CourseId],
        [IDL.Vec(LessonProgress)],
        ['query'],
      ),
    'getMyPoints' : IDL.Func([], [IDL.Nat], ['query']),
    'getMyQuizAttempts' : IDL.Func(
        [CourseId, IDL.Text],
        [IDL.Vec(QuizAttempt)],
        ['query'],
      ),
    'getReportingData' : IDL.Func(
        [],
        [IDL.Vec(LearnerCourseReport)],
        ['query'],
      ),
    'getUserCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
    'incrementCourseViews' : IDL.Func([CourseId], [], []),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'loginEmailUser' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : EmailUserPublic, 'err' : IDL.Text })],
        ['query'],
      ),
    'markLessonComplete' : IDL.Func([CourseId, IDL.Text], [], []),
    'registerEmailUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : EmailUserPublic, 'err' : IDL.Text })],
        [],
      ),
    'resetDatabase' : IDL.Func([], [], []),
    'resetEmailUsers' : IDL.Func([], [], []),
    'seedFirstAdmin' : IDL.Func([], [], []),
    'setUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'submitQuizAttempt' : IDL.Func(
        [CourseId, IDL.Text, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'submitReview' : IDL.Func([CourseId, IDL.Nat, IDL.Text], [], []),
    'updateCourse' : IDL.Func([CourseId, UpdateCourseDto], [Course], []),
    'updateEmailUserRole' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateMyProfile' : IDL.Func([UpdateUserProfileDto], [], []),
  });
};

export const init = ({ IDL }) => { return []; };