/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ProfileId = IDL.Nat;
export const Time = IDL.Int;
export const UserProfile = IDL.Record({
  'id' : ProfileId,
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Time,
  'role' : UserRole,
  'email' : IDL.Text,
  'avatarUrl' : IDL.Text,
});
export const CreateUserProfileDto = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const UpdateUserProfileDto = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'doesAdminExist' : IDL.Func([], [IDL.Bool], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getUserCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
  'getUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isInstructor' : IDL.Func([], [IDL.Bool], ['query']),
  'registerProfile' : IDL.Func([CreateUserProfileDto], [UserProfile], []),
  'seedFirstAdmin' : IDL.Func([], [], []),
  'setUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'updateMyProfile' : IDL.Func([UpdateUserProfileDto], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ProfileId = IDL.Nat;
  const Time = IDL.Int;
  const UserProfile = IDL.Record({
    'id' : ProfileId,
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Time,
    'role' : UserRole,
    'email' : IDL.Text,
    'avatarUrl' : IDL.Text,
  });
  const CreateUserProfileDto = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
  });
  const UpdateUserProfileDto = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'doesAdminExist' : IDL.Func([], [IDL.Bool], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getUserCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
    'getUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isInstructor' : IDL.Func([], [IDL.Bool], ['query']),
    'registerProfile' : IDL.Func([CreateUserProfileDto], [UserProfile], []),
    'seedFirstAdmin' : IDL.Func([], [], []),
    'setUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'updateMyProfile' : IDL.Func([UpdateUserProfileDto], [], []),
  });
};

export const init = ({ IDL }) => { return []; };