/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Badge { 'name' : string, 'awardedAt' : Time }
export interface Course {
  'id' : CourseId,
  'title' : string,
  'duration' : bigint,
  'isPublished' : boolean,
  'views' : bigint,
  'createdAt' : Time,
  'tags' : Array<string>,
  'instructorId' : Principal,
  'lessonCount' : bigint,
}
export type CourseId = bigint;
export interface CreateCourseDto { 'title' : string }
export interface CreateUserProfileDto { 'name' : string, 'email' : string }
export interface EmailUserPublic {
  'id' : string,
  'name' : string,
  'createdAt' : Time,
  'role' : string,
  'email' : string,
}
export interface Enrollment {
  'completedAt' : [] | [Time],
  'principal' : Principal,
  'isCompleted' : boolean,
  'enrolledAt' : Time,
  'courseId' : CourseId,
}
export interface LearnerCourseReport {
  'completedAt' : [] | [Time],
  'learnerPrincipal' : Principal,
  'startedAt' : [] | [Time],
  'isCompleted' : boolean,
  'completedLessons' : bigint,
  'enrolledAt' : Time,
  'courseId' : CourseId,
}
export interface LessonProgress {
  'lessonId' : string,
  'completedAt' : [] | [Time],
  'isCompleted' : boolean,
  'courseId' : CourseId,
}
export type ProfileId = bigint;
export interface QuizAttempt {
  'completedAt' : Time,
  'score' : bigint,
  'pointsEarned' : bigint,
  'quizId' : string,
  'courseId' : CourseId,
  'attemptNumber' : bigint,
}
export interface Review {
  'principal' : Principal,
  'createdAt' : Time,
  'comment' : string,
  'rating' : bigint,
  'courseId' : CourseId,
}
export type Time = bigint;
export interface UpdateCourseDto {
  'title' : string,
  'duration' : bigint,
  'isPublished' : boolean,
  'tags' : Array<string>,
  'lessonCount' : bigint,
}
export interface UpdateUserProfileDto { 'name' : string, 'email' : string }
export interface UserProfile {
  'id' : ProfileId,
  'principal' : Principal,
  'name' : string,
  'createdAt' : Time,
  'role' : UserRole,
  'email' : string,
  'avatarUrl' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'awardBadge' : ActorMethod<[Principal, string], undefined>,
  'completeCourse' : ActorMethod<[CourseId], undefined>,
  'createCourse' : ActorMethod<[CreateCourseDto], Course>,
  'createProfile' : ActorMethod<[CreateUserProfileDto], UserProfile>,
  'deleteEmailUser' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'doesAdminExist' : ActorMethod<[], boolean>,
  'enrollCourse' : ActorMethod<[{ 'courseId' : CourseId }], undefined>,
  'enrollLearnerByEmail' : ActorMethod<[CourseId, string], undefined>,
  'getAllEmailUsers' : ActorMethod<[], Array<EmailUserPublic>>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCourseAttendees' : ActorMethod<[CourseId], Array<UserProfile>>,
  'getCourseReviews' : ActorMethod<[CourseId], Array<Review>>,
  'getCourses' : ActorMethod<[], Array<Course>>,
  'getEmailUserById' : ActorMethod<
    [string],
    { 'ok' : EmailUserPublic } |
      { 'err' : string }
  >,
  'getEnrollments' : ActorMethod<[Principal], Array<Enrollment>>,
  'getMyBadges' : ActorMethod<[], Array<Badge>>,
  'getMyCourseCompletions' : ActorMethod<[], Array<Enrollment>>,
  'getMyCourses' : ActorMethod<[], Array<Course>>,
  'getMyLessonProgress' : ActorMethod<[CourseId], Array<LessonProgress>>,
  'getMyPoints' : ActorMethod<[], bigint>,
  'getMyQuizAttempts' : ActorMethod<[CourseId, string], Array<QuizAttempt>>,
  'getReportingData' : ActorMethod<[], Array<LearnerCourseReport>>,
  'getUserCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], UserProfile>,
  'incrementCourseViews' : ActorMethod<[CourseId], undefined>,
  'isAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'loginEmailUser' : ActorMethod<
    [string, string],
    { 'ok' : EmailUserPublic } |
      { 'err' : string }
  >,
  'markLessonComplete' : ActorMethod<[CourseId, string], undefined>,
  'registerEmailUser' : ActorMethod<
    [string, string, string, string],
    { 'ok' : EmailUserPublic } |
      { 'err' : string }
  >,
  'resetDatabase' : ActorMethod<[], undefined>,
  'resetEmailUsers' : ActorMethod<[], undefined>,
  'seedFirstAdmin' : ActorMethod<[], undefined>,
  'setUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'submitQuizAttempt' : ActorMethod<
    [CourseId, string, bigint, bigint],
    undefined
  >,
  'submitReview' : ActorMethod<[CourseId, bigint, string], undefined>,
  'updateCourse' : ActorMethod<[CourseId, UpdateCourseDto], Course>,
  'updateEmailUserRole' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateMyProfile' : ActorMethod<[UpdateUserProfileDto], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];